# Generated by Django 5.0.6 on 2024-06-27 04:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['user_name']},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='father_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_mother_name', message='This field must be alphabetic', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mother_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_mother_name', message='This field must be alphabetic', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_mother_name', message='This field must be alphabetic', regex='^[a-zA-Z]*$')]),
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['user_name'], name='tweet_useri_user_na_eb2cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['city'], name='tweet_useri_city_742763_idx'),
        ),
    ]
